/*
 * Class:        GeometricGen
 * Description:  random variate generator for the geometric distribution
 * Environment:  Java
 * Software:     SSJ 
 * Copyright (C) 2001  Pierre L'Ecuyer and Universite de Montreal
 * Organization: DIRO, Universite de Montreal
 * @author       
 * @since

 * SSJ is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License (GPL) as published by the
 * Free Software Foundation, either version 3 of the License, or
 * any later version.

 * SSJ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * A copy of the GNU General Public License is available at
   <a href="http://www.gnu.org/licenses">GPL licence site</a>.
 */
package umontreal.ssj.randvar;
import umontreal.ssj.rng.*;
import umontreal.ssj.probdist.*;

/**
 * This class implements a random variate generator for the *geometric*
 * distribution. Its has parameter @f$p@f$ and mass function
 * @anchor REF_randvar_GeometricGen_eq_fgeom
 * @f[
 *   p(x) = p(1-p)^x \mbox{ for } x=0,1,2,…, \tag{fgeom}
 * @f]
 * where @f$0\le p\le1@f$. Random variates are generated by calling
 * inversion on the distribution object.
 *
 * <div class="SSJ-bigskip"></div>
 *
 * @ingroup randvar_discrete
 */
public class GeometricGen extends RandomVariateGenInt {
   private double p;

   /**
    * Creates a geometric random variate generator with parameter @f$p@f$,
    * using stream `s`.
    */
   public GeometricGen (RandomStream s, double p) {
      super (s, new GeometricDist(p));
      setParams (p);
   }

   /**
    * Creates a new generator for the distribution `dist`, using stream
    * `s`.
    */
   public GeometricGen (RandomStream s, GeometricDist dist) {
      super (s, dist);
      if (dist != null)
         setParams (dist.getP());
   }
 
    
   public int nextInt () {
      return GeometricDist.inverseF (p, stream.nextDouble());
   }

/**
 * Generates a *geometric* random variate with parameter @f$p = @f$&nbsp;`p`,
 * using stream `s`, by inversion.
 */
public static int nextInt (RandomStream s, double p) {
      return GeometricDist.inverseF (p, s.nextDouble());
   }

   /**
    * Returns the parameter @f$p@f$ of this object.
    */
   public double getP() {
      return p;
   }

   /**
    * Sets the parameter @f$n@f$ and @f$p@f$ of this object.
    */
   protected void setParams (double p) {
      if (p < 0.0 || p > 1.0)
         throw new IllegalArgumentException ("p not in range [0, 1]");
      this.p = p;
   }
}