/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Lecuyer' at '12/21/16 5:10 PM' with Gradle 3.0
 *
 * @author Lecuyer, @date 12/21/16 5:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
